services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c"]
    command: ["ollama serve && ollama run deepseek-r1:14b"]
    # Use NVIDIA runtime
    runtime: nvidia  
    environment:
    # Make all GPUs visible to the container
      - NVIDIA_VISIBLE_DEVICES=all  

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama:
  open-webui:
