version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c"]
    # download the model if you dont already have it, its about 1.1GB
    command: ["ollama serve && ollama run deepseek-r1:1.5b"] 
    # set a minimum memory to use for the container, this will ensure the 1.5b runs completely in memory
    mem_reservation: 4g 

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
# ollama volume defined so you don't need to download the model every time.
# open-webui volume defined to retain user access/history persistence.
volumes:
  ollama:
  open-webui:
