services:
  ollama:
    image: ollama/ollama  # Use the standard image
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c"]
    command: ["ollama serve && ollama run deepseek-r1:14b"]
    deploy:
      resources:
        reservations:
          memory: 4g  # Reserve memory for the container
          devices:
            - capabilities: [gpu]  # Request GPU resources
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible to the container

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
